ats.url=${ATS_URL}
internal.token=${INTERNAL_TOKEN}

db.url=${DB_URL}
db.username=${DB_USERNAME}
db.password=${DB_PASSWORD}

ats.allowed.origin=${ATS_ALLOWED_ORIGIN}
swagger.allowed.origin=${SWAGGER_ALLOWED_ORIGIN}